#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : os_vif
Version  : 1.17.0
Release  : 13
URL      : https://files.pythonhosted.org/packages/08/f0/05b4b39f6c091fc5a54b97ff6933c4305c44cf0f3b0774257d0b4414aece/os_vif-1.17.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/08/f0/05b4b39f6c091fc5a54b97ff6933c4305c44cf0f3b0774257d0b4414aece/os_vif-1.17.0.tar.gz
Summary  : A library for plugging and unplugging virtual interfaces in OpenStack.
Group    : Development/Tools
License  : Apache-2.0
Requires: os_vif-license = %{version}-%{release}
Requires: os_vif-python = %{version}-%{release}
Requires: os_vif-python3 = %{version}-%{release}
Requires: debtcollector
Requires: netaddr
Requires: oslo.concurrency
Requires: oslo.config
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.privsep
Requires: oslo.versionedobjects
Requires: ovsdbapp
Requires: pbr
Requires: pyroute2
Requires: six
Requires: stevedore
BuildRequires : buildreq-distutils3
BuildRequires : debtcollector
BuildRequires : netaddr
BuildRequires : oslo.concurrency
BuildRequires : oslo.config
BuildRequires : oslo.i18n
BuildRequires : oslo.log
BuildRequires : oslo.privsep
BuildRequires : oslo.versionedobjects
BuildRequires : ovsdbapp
BuildRequires : pbr
BuildRequires : pyroute2
BuildRequires : six
BuildRequires : stevedore

%description
========================
Team and repository tags
========================
.. image:: https://governance.openstack.org/tc/badges/os-vif.svg
:target: https://governance.openstack.org/tc/reference/tags/index.html

%package license
Summary: license components for the os_vif package.
Group: Default

%description license
license components for the os_vif package.


%package python
Summary: python components for the os_vif package.
Group: Default
Requires: os_vif-python3 = %{version}-%{release}

%description python
python components for the os_vif package.


%package python3
Summary: python3 components for the os_vif package.
Group: Default
Requires: python3-core

%description python3
python3 components for the os_vif package.


%prep
%setup -q -n os_vif-1.17.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567791761
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/os_vif
cp LICENSE %{buildroot}/usr/share/package-licenses/os_vif/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/os_vif/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
