#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : os_vif
Version  : 2.0.0
Release  : 15
URL      : https://files.pythonhosted.org/packages/03/8b/e983b3930415388459db486fef7c0d851f38fe84d7ce6a86817c1067d21a/os_vif-2.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/03/8b/e983b3930415388459db486fef7c0d851f38fe84d7ce6a86817c1067d21a/os_vif-2.0.0.tar.gz
Summary  : A library for plugging and unplugging virtual interfaces in OpenStack.
Group    : Development/Tools
License  : Apache-2.0
Requires: os_vif-license = %{version}-%{release}
Requires: os_vif-python = %{version}-%{release}
Requires: os_vif-python3 = %{version}-%{release}
Requires: debtcollector
Requires: netaddr
Requires: oslo.concurrency
Requires: oslo.config
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.privsep
Requires: oslo.versionedobjects
Requires: ovsdbapp
Requires: pbr
Requires: pyroute2
Requires: six
Requires: stevedore
BuildRequires : buildreq-distutils3
BuildRequires : debtcollector
BuildRequires : netaddr
BuildRequires : oslo.concurrency
BuildRequires : oslo.config
BuildRequires : oslo.i18n
BuildRequires : oslo.log
BuildRequires : oslo.privsep
BuildRequires : oslo.versionedobjects
BuildRequires : ovsdbapp
BuildRequires : pbr
BuildRequires : pyroute2
BuildRequires : six
BuildRequires : stevedore

%description
========================
Team and repository tags
========================

.. image:: https://governance.openstack.org/tc/badges/os-vif.svg
    :target: https://governance.openstack.org/tc/reference/tags/index.html

.. Change things from this point on

======
os-vif
======

.. image:: https://img.shields.io/pypi/v/os-vif.svg
    :target: https://pypi.org/project/os-vif/
    :alt: Latest Version

.. image:: https://img.shields.io/pypi/dm/os-vif.svg
    :target: https://pypi.org/project/os-vif/
    :alt: Downloads

A library for plugging and unplugging virtual interfaces in OpenStack.

* License: Apache License, Version 2.0
* Documentation: https://docs.openstack.org/os-vif/latest/
* Source: https://opendev.org/openstack/os-vif
* Bugs: https://bugs.launchpad.net/os-vif
* Release Notes: https://docs.openstack.org/releasenotes/os-vif

%package license
Summary: license components for the os_vif package.
Group: Default

%description license
license components for the os_vif package.


%package python
Summary: python components for the os_vif package.
Group: Default
Requires: os_vif-python3 = %{version}-%{release}

%description python
python components for the os_vif package.


%package python3
Summary: python3 components for the os_vif package.
Group: Default
Requires: python3-core
Provides: pypi(os-vif)

%description python3
python3 components for the os_vif package.


%prep
%setup -q -n os_vif-2.0.0
cd %{_builddir}/os_vif-2.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583195845
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/os_vif
cp %{_builddir}/os_vif-2.0.0/LICENSE %{buildroot}/usr/share/package-licenses/os_vif/294b43b2cec9919063be1a3b49e8722648424779
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/os_vif/294b43b2cec9919063be1a3b49e8722648424779

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
